// style.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollContainer: {
    flexGrow: 1,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  card: {
    width: '45%',
    margin: 5,
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  subHeaderText: {
    fontSize: 14,
    color: '#555',
    marginVertical: 5,
    textAlign: 'center',
  },
  cardCount: {
    fontSize: 24,
    color: '#333',
    marginTop: 10,
  },
  cardName: {
    fontSize: 18,
    color: '#333',
    marginTop: 5,
    fontWeight: 'bold',
  },
  followUpSection: {
    padding: 10,
    marginTop: -10,
    shadowRadius: 5,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#f0f0f0',
  },
  UpcomingSection: {
    padding: 10,
    marginTop: 15,
    shadowRadius: 5,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#f0f0f0',
  },
  TaskSection: {
    padding: 10,
    marginTop: 15,
    shadowRadius: 5,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#f0f0f0',
  },
  noFollowUpsText: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
    marginTop: 10,
  },
  followUpContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  followUpCard: {
    width: 150,
    height: 100,
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    margin: 5,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  dateTimeBox: {
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    padding: 10,
    width: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateTimeText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  dateTimeTextSmall: {
    fontSize: 10,
    fontWeight: 'normal',
  },
  detailText: {
    fontSize: 14,
    marginBottom: 5,
  },
  bold: {
    fontWeight: 'bold',
  },
  followUpName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 5,
  },
  followUpDate: {
    fontSize: 14,
    color: '#555',
    marginTop: 2,
  },
  modalContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  leftButtons: {
    flexDirection: 'row',
  },
  rightIcons: {
    flexDirection: 'row',
  },
  iconButton: {
    padding: 5,
    marginLeft: 10,
  },
  acceptButton: {
    backgroundColor: '#28a745',
    padding: 10,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  UpcomingrescheduleButton: {
    backgroundColor: '#007bff',
    padding: 10,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  rescheduleButton: {
    backgroundColor: '#007bff',
    padding: 10,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  detailsBox: {
    flex: 1,
    marginRight: 10,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalCard: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 10,
    width: '90%',
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  closeButton: {
    padding: 10,
  },
  clinicName: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: '#ccc',
    marginHorizontal: 10,
  },
  headerText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#555',
    textTransform: 'uppercase',
  },
});
